routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserExperienceController;
use App\Http\Controllers\VariableController;
use App\Models\UserExperience;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


define('PAGINATION_COUNT',6);
Route::group(['prefix'=>'Admin' , 'Middleware'=>'auth' ],function (){
    Auth::routes();
    Route::get('/Password', [UserController::class,'showChangePasswordForm'])->name('Password');
    Route::post('changePassword', [UserController::class,'changePassword'])->name('changePassword');
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index']);
    Route::resource('role',RoleController::class);
    Route::resource('users',UserController::class);
    Route::resource('service',ServiceController::class);
    Route::resource('project',ProjectController::class);
    Route::resource('slider',SliderController::class);
    Route::resource('news',NewsController::class);
    Route::resource('category',CategoryController::class);
    Route::resource('team',TeamController::class);
    Route::resource('userExperience',UserExperienceController::class);
    Route::resource('partners',PartnerController::class);
    Route::get('about',[App\Http\Controllers\VariableController::class,'getAbout']);
    Route::get('getAbout',[App\Http\Controllers\VariableController::class,'create']);
    Route::post('editAbout',[App\Http\Controllers\VariableController::class,'setAbout']);
    Route::get('contact_info',[App\Http\Controllers\VariableController::class,'getInfo']);
    Route::post('edit_contact_info',[App\Http\Controllers\VariableController::class,'setInfo']);
    Route::get('getMap',[App\Http\Controllers\VariableController::class,'getMap']);
    Route::post('setMap',[App\Http\Controllers\VariableController::class,'setMap']);


});
//route for multi languages

Route::get('changeLang/{lang}',function ($lang){
    App::setLocale($lang);
    Session::put('locale', $lang);
    \LaravelLocalization::setLocale($lang);
    $url = \LaravelLocalization::getLocalizedURL(App::getLocale(), \URL::previous());
    return Redirect::to($url);
});

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){

        Route::get('/', [App\Http\Controllers\HomeController::class, 'home']);
        Route::post('/search', [App\Http\Controllers\HomeController::class, 'search'])->name('search');
        Route::get('/search', [App\Http\Controllers\HomeController::class, 'index_search'])->name('index_search');
        Route::get('/team', [App\Http\Controllers\TeamController::class, 'show']);
//        Route::get('/contact', function (){
//            return view('front/contact');
//        });
        Route::get('/contact', [ContactUsController::class, 'create']);
        Route::post('/contact', [ContactUsController::class, 'sendEmail'])->name('send.email');

        Route::get('/service', [App\Http\Controllers\ServiceController::class, 'show'])->name('search_service');
        Route::get('/news', [App\Http\Controllers\NewsController::class, 'show']);
        Route::get('/news/{id}', [App\Http\Controllers\NewsController::class, 'show_detail'])->name('search_news');
        Route::get('/project', [App\Http\Controllers\ProjectController::class, 'show'])->name('search_project');
        Route::get('project/{id}', [App\Http\Controllers\ProjectController::class, 'show_detail']);
        Route::get('about',function(){
            if(\LaravelLocalization::getCurrentLocale()=='ar')
                $about=App\Models\Variable::where('name','about_ar')->first();
            else
                $about=App\Models\Variable::where('name','about_en')->first();
            return View::make('front/about-company')->with('about',$about);
        });
});

Route::get('/productsCat', [App\Http\Controllers\ProjectController::class, 'productsCat']);

app/Models/UserExperience.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserExperience extends Model implements TranslatableContract
{
    use HasFactory, Translatable;

    public $translatedAttributes = ['name', 'text' ];
    protected $fillable=[];
    public function UserExperienceTranslation()
    {
        return $this->hasMany(UserExperienceTranslation::class,'user_experience_id');
    }
    public function scopeSelect($query)
    {
        return $query->orderBy('id','DESC');
    }
}

app/Http/Controllers/UserExperienceController.php
<?php

namespace App\Http\Controllers;

use App\Models\UserExperience;
use Illuminate\Http\Request;

class UserExperienceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userExperiences = UserExperience::select()->paginate(PAGINATION_COUNT);
        return view('admin.UserExperience.index' , compact('userExperiences'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.UserExperience.create' );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $validation =  $this->validate( $request, [
                'name:ar' => 'required',
                'name:en' => 'required',
                'text:ar' => 'required',
                'text:en' => 'required',
            ]);

            $userExperiences = UserExperience::create([
                'name:ar'  => $request -> {'name:ar'},
                'name:en'  => $request -> {'name:en' },
                'text:ar'  => $request -> {'text:ar'},
                'text:en'  => $request -> {'text:en' },
            ]);

            return redirect()->back()->with(['success'=>'تم الحفظ بنجاح']);
        }catch (\Exception $ex){
            return redirect()->back()->with(['error'=>'حدث خطأ ما']);

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\UserExperience  $userExperience
     * @return \Illuminate\Http\Response
     */
    public function show()
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\UserExperience  $userExperience
     * @return \Illuminate\Http\Response
     */
    public function edit(UserExperience $userExperience)
    {
        $userExperiences = UserExperience::select()->find($userExperience->id);
        if(!$userExperiences){
            return redirect()->route('Admin.UserExperience')->with(['error'=>'هذه التجربة غير موجودة']);
        }
        return view('admin.UserExperience.edit',compact('userExperiences' ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\UserExperience  $userExperience
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $ID)
    {

        try {
            $userExperience = UserExperience::where('id', $ID)->first();
            $validation =  $this->validate( $request, [
                'name:ar' => 'required',
                'name:en' => 'required',
                'text:ar' => 'required',
                'text:en' => 'required',
            ]);
            $userExperience->update([
                'name:ar'  => $request -> {'name:ar'},
                'name:en'  => $request -> {'name:en' },
                'text:ar'  => $request -> {'text:ar'},
                'text:en'  => $request -> {'text:en' },
            ]);

            return redirect('Admin/userExperience')->with(['success'=>'تم الحفظ بنجاح']);
        }catch (\Exception $ex){
            return redirect()->back()->with(['error'=>'حدث خطأ ما']);

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\UserExperience  $userExperience
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {

        try {
            $userExperience = UserExperience::find($request->delet_id);
            if (!$userExperience) {
                return redirect()->back()->with('error','هناك خطا ما يرجي المحاوله فيما بعد');
            }

            $userExperience->delete();

            return redirect()->back()->with('success','تم الحذف بنجاح');

        } catch (\Exception $ex) {
            return redirect()->back()->with('error','هناك خطا ما يرجي المحاوله فيما بعد');
        }
    }
}

resources/views/admin/userExperience/edit.blade.php
@extends('layouts.admin')
@section('title')
    | تجارب المستخدمين | تعديل
@endsection
@section('content')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{url('Admin/dashboard')}}">لوحة التحكم </a>
                                </li>
                                <li class="breadcrumb-item"><a href="{{url('Admin/service')}}"> تجارب المستخدمين  </a>
                                </li>
                                <li class="breadcrumb-item active"> تعديل البيانات
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic form layout section start -->
                <section id="basic-form-layouts">
                    <div class="row match-height">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <a class="heading-elements-toggle"><i
                                            class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                @include('admin.includes.alerts.success')
                                @include('admin.includes.alerts.errors')
                                <div class="card-content collapse show">
                                    <div class="card-body">
                                        <form class="form" action="{{route('userExperience.update',$userExperiences->id)}}" method="POST"
                                              enctype="multipart/form-data">
                                            @method('PATCH')
                                            @csrf

                                            <div class="form-body">
                                                <h4 class="form-section"><i class="ft-home"></i> بيانات التجربة </h4>

                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="name"> الاسم AR</label>
                                                            <input type="text"
                                                                   value="{{ $userExperiences->{'name:ar'} }}"
                                                                   id="name"
                                                                   class="form-control"
                                                                   placeholder="ادخل اسم الشخص "
                                                                   name="name:ar">
                                                            @error("name")
                                                            <span class="text-danger">{{$message}} </span>
                                                            @enderror
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="name"> الاسم EN </label>
                                                            <input type="text"
                                                                   value="{{ $userExperiences->{'name:en'} }}"
                                                                   id="name"
                                                                   class="form-control"
                                                                   placeholder="ادخل اسم الشخص"
                                                                   name="name:en">
                                                            @error("name")
                                                            <span class="text-danger">{{$message}} </span>
                                                            @enderror
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="row">
                                                    <div class="col-md-12" >
                                                        <div class="form-group">
                                                            <label for="text"> التجربة AR</label>
                                                            <textarea type="text"
                                                                      id="text"
                                                                      rows="5"
                                                                      class="form-control"
                                                                      placeholder="ادخل النص "
                                                                      name="text:ar">
                                                                {{ $userExperiences->{'text:ar'} }}
                                                            @error("text")
                                                            <span class="text-danger">{{$message}} </span>
                                                            @enderror
                                                            </textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-12" >
                                                        <div class="form-group">
                                                            <label for="text"> التجربة EN </label>
                                                            <textarea type="text"
                                                                      id="text"
                                                                      rows="5"
                                                                      class="form-control"
                                                                      placeholder="ادخل النص "
                                                                      name="text:en">
                                                                {{ $userExperiences->{'text:en'} }}
                                                            @error("text")
                                                            <span class="text-danger">{{$message}} </span>
                                                            @enderror
                                                            </textarea>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                            <div class="form-actions">
                                                <button type="button" class="btn btn-outline-warning box-shadow-1 mr-1"
                                                        onclick="history.back();">
                                                    <i class="ft-x"></i> تراجع
                                                </button>
                                                <button type="submit" class="btn btn-outline-primary box-shadow-1">
                                                    <i class="la la-check-square-o"></i> حفظ
                                                </button>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- // Basic form layout section end -->
            </div>
        </div>
    </div>

@endsection

resources/views/admin/userExperience/index.blade.php
@extends('layouts.admin')
@section('title')
    | تجارب المستخدمين
@endsection
@section('content')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{url('admin\dashboard')}}">لوحة التحكم</a>
                                </li>
                                <li class="breadcrumb-item active"> قائمة التجارب
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- DOM - jQuery events table -->
                <section id="dom">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <a class="heading-elements-toggle"><i
                                            class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                        </ul>
                                    </div>
                                </div>

                                @include('admin.includes.alerts.success')
                                @include('admin.includes.alerts.errors')

                                <div class="card-content collapse show">
                                    <div class="card-body card-dashboard" style="text-align: center">
                                        <table
                                            class="table display table-striped table-bordered ">
                                            <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">الاسم </th>
                                                <th scope="col">التجربة AR</th>
                                                <th scope="col"> التجربة EN</th>
                                                <th scope="col">العمليات</th>
                                            </tr>
                                            </thead>
                                            <tbody>

                                    @isset($userExperiences)
                                        @foreach ($userExperiences as $key => $userExperience)
                                            <tr>
                                                <td>{{ ++$key }}</td>
                                                <td>{{ $userExperience->{'name:ar'} }} <br> {{ $userExperience->{'name:en'} }}</td>
                                                <td>
                                                <?php $text = strip_tags( $userExperience->{'text:ar'});
                                                $new = trim($text);
                                                    echo substr($new,0,50);?></td>
                                                <td>
                                                <?php $text = strip_tags($userExperience->{'text:en'});
                                                $new = trim($text);
                                                echo substr($new,0,50);?></td>

                                                <td>
{{--                                                    @can('تعديل التجربة')--}}
                                                        <a href="{{ route('userExperience.edit', $userExperience->id) }}" class="btn btn-sm btn-outline-info box-shadow-1"
                                                           title="تعديل"><i class="la la-pencil-square"></i> تعديل</a>
{{--                                                    @endcan--}}

{{--                                                    @can('حذف التجربة')--}}
                                                    <button class=" btn btn-sm btn-outline-danger box-shadow-1" data-delid={{$userExperience->id}} data-toggle="modal" data-target="#delete"
                                                            title="حذف" >
                                                        <i class="la la-trash"></i>حذف </button>
{{--                                                    @endcan--}}
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endisset

                                            </tbody>
                                        </table>
                                        {{$userExperiences->links('admin.pagination')}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        @isset($userExperience)
                        <div class="modal fade" id="delete" tabindex="-1" role="dialog"
                             aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-sm" role="document">>
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal"
                                                aria-hidden="true">&times;</button>
                                    </div>

                                    <!-- Modal -->
                                    <form action="{{url("Admin/userExperience/{$userExperience->id}")}}" method="post">
                                        {{method_field('DELETE')}}
                                        {{csrf_field()}}
                                        <div class="modal-body">
                                            <h4>   هل أنت متأكد من حذف هذا العنصر؟</h4>
                                            <input type="hidden" name="delet_id" id="del_id" value="">

                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-success" data-dismiss="modal">إلغاء</button>
                                            <button type="submit" class="btn btn-warning">موافق</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        @endisset
                    </div>
                </section>

            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="{{asset('admin/js/scripts/delete.js')}}" type="text/javascript"></script>
@endsection